// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Apka.API.Data;

namespace Apka.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220313191251_StreamersTableCreate")]
    partial class StreamersTableCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("apka.Models.Streamers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AverageViewers")
                        .HasColumnType("integer");

                    b.Property<string>("Channel")
                        .HasColumnType("text");

                    b.Property<int>("Followers")
                        .HasColumnType("integer");

                    b.Property<int>("FollowersGained")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<bool>("Mature")
                        .HasColumnType("boolean");

                    b.Property<bool>("Partnered")
                        .HasColumnType("boolean");

                    b.Property<int>("PeakViewers")
                        .HasColumnType("integer");

                    b.Property<int>("StreamTime")
                        .HasColumnType("integer");

                    b.Property<decimal>("ViewsGained")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("WatchTime")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("Streamers");
                });
#pragma warning restore 612, 618
        }
    }
}
